Config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("autenticación.urls")),
    path('', include("usuario.urls")),
    path('', include("productos.urls")),
    path('', include("carrito.urls")),
    path('', include("orden.urls")),
]

carrito/urls.py
from django.urls import path
from .views import *

app_name = "carrito"

urlpatterns = [
    path('AgregarProducto/<int:producto_id>/', AgregarProducto, name='AgregarProducto'),
    path('EliminarProducto/<int:producto_id>/', EliminarProducto, name='EliminarProducto'),
    path('DecrementarProducto/<int:producto_id>/', DecrementarProducto, name='DecrementarProducto'),
    path('LimpiarCarrito/', LimpiarCarrito, name='LimpiarCarrito'),
]

orden/urls.py
from django.urls import path
from .views import *
from orden.views import OrderDetail, OrderList, process_order
from orden import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('process_order/', process_order, name='process_order'),
    path('me/', login_required(OrderList.as_view(), login_url='/autenticacion/acceder'), name='order_list'),
    path('<int:pk>', login_required(OrderDetail.as_view(), login_url='/autenticacion/acceder'), name='order_detail'),
    path('listadoOrden/',OrderList.as_view(), name = 'listadoOrden'),
    path('detalle/<int:pk>/',views.Order, name = 'detalle'),
]

productos/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', inicio, name="inicio"),
    path('productos/',productos, name="productos"),
    path('promociones/',promociones, name="promociones"),
    path('carrito/',carrito, name="carrito"),
]

productos/models.py
from django.db import models

class Tipo(models.Model):
        id = models.IntegerField(primary_key=True)
        descripcion = models.CharField(max_length=50)

        def __str__(self):
            return self.descripcion

        class Meta:
            db_table = 'Tipo'

class Producto(models.Model):
        id = models.IntegerField(primary_key=True)
        nombre = models.CharField(max_length=50)
        especificacion = models.CharField(max_length=100, blank=True, null= True)
        stock=models.IntegerField(default=0) 
        precio_venta=models.FloatField(max_length=10,default=0)
        img = models.CharField(max_length=50)
        id_tipo = models.ForeignKey(Tipo, on_delete=models.CASCADE)

        def __str__(self):
                return self.nombre

        class Meta:
                db_table = 'Producto'

class Canal(models.Model):
        descripcion = models.CharField(max_length=50)

        def __str__(self):
            return self.descripcion

        class Meta:
                db_table = 'Canal'

class Promociones(models.Model):
        especificacion = models.CharField(max_length=100)
        fec_ini = models.DateTimeField(auto_now_add=True)
        fec_fin = models.DateField(max_length=20)
        precio_nuevo = models.FloatField(max_length=20, default=0)
        stock=models.IntegerField(default=0) 
        estado = models.CharField(max_length=12, default="Vigente") 
        img = models.CharField(max_length=50)   
        producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
        canal = models.ForeignKey(Canal, on_delete=models.CASCADE)

        def __str__(self):
            return (self.nombre)
        
        class Meta:
                db_table = 'Promociones'

productos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Producto, Tipo, Promociones, Canal



def inicio(request):   
    prod = Producto.objects.filter(id_tipo=2)
    return render(request,'index.html', {"productos":prod})

def productos(request):  
    Tip=Tipo.objects.all() 
    produ = Producto.objects.all()   
    return render(request,'productos.html', {"prod":produ,"tipo":Tip})     

def promociones(request):  
    Can=Canal.objects.all() 
    promo = Promociones.objects.all()   
    return render(request,'promociones.html', {"promo":promo,"Can":Can})   

def carrito(request):
    return render( request, 'widget.html', {})

productos/templates/base.html
<!doctype html>
<html lang="en">

<head>
    {% load static %}
    <!-- href="../static/imagenes/icono.ico"> por buenas practicas usar load -->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS   -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="{% static 'estilos.css' %}" type="text/css" rel="stylesheet" media="screen,projection" />
    <title>Muebleria Los Pinos</title>
    <link rel="icon" type="image/ico" href="">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top btn-info">
        <a class="navbar-brand" href="/" class="d-inline-block align-top" alt="" loading="lazy">Muebleria Los Pinos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav mr-auto ">
                <a class="nav-link {% if request.path == '/' %} active {% endif %}" href="/">Inicio</a>
                <a class="nav-link {% if request.path == '/productos/' %} active {% endif %}" href="/productos/">Productos</a>
                <a class="nav-link {% if request.path == '/Promociones/' %} active {% endif %}" href="/promociones/">Promociones</a>
                <a class="nav-link {% if request.path == '/carrito/' %} active {% endif %}" href="/carrito/">Carrito</a>

            </div>
            <div class="navbar-nav ">
                {%if user.is_authenticated%}
                <a class="nav-link" href="#">Hola: {{user.username}}</a>
                <a class="nav-link" href="{%url 'salir'%}">Cerrar Sesión</a> {%else%}
                <a class="nav-link {% if request.path == '/registro/' %} active {% endif %}" href="/registro/">Registrate</a>
                <a class="nav-link {% if request.path == '/acceder/' %} active {% endif %}" href="/acceder/">Ingresa a tu Cuenta</a> {%endif%}
            </div>
        </div>
    </nav>

    <!-- contenido Cambiante -->
    <div>
        {% if messages %}
        <div class="row mt-5 mb-3">
            <div class="col-12">
                {%for message in messages%}
                <div class="alert alert-{{message.tags}}">
                    {{message}}
                </div>
                {%endfor%}
            </div>
        </div>
        {% endif %}{% block content %} {% endblock %}
    </div>


    <!-- Footer -->
    <footer class="page-footer font-small btn-dark">

        <div class="bg-info">
            <div class="container">

                <!-- Grid row-->
                <div class="row py-4 d-flex align-items-center">

                    <!-- Grid column -->
                    <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">

                        <h6 class="mb-0">Muebleria Los Pinos!</h6>
                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-md-6 col-lg-7 text-center text-md-right">

                        <!-- Facebook -->
                        <a class="fb-ic">
                            <img src="{% static 'imagenes/fac.jpg' %}" width="40" height="20">
                        </a>
                        <!-- Wasap -->
                        <a class="tw-ic">
                            <img src="{% static 'imagenes/wha.jpg' %}" width="30" height="20">
                        </a>

                        <!--Instagram-->
                        <a class="ins-ic">
                            <img src="{% static 'imagenes/ins.jpg' %}" width="20" height="20">
                        </a>

                    </div>
                    <!-- Grid column -->

                </div>
                <!-- Grid row-->

            </div>
        </div>

        <!-- Footer Links -->
        <div class="container text-center text-md-left mt-5">

            <!-- Grid row -->
            <div class="row mt-3">

                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

                    <!-- Content -->
                    <h6 class="text-uppercase font-weight-bold">Company name</h6>
                    <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <div>
                        <img src="{% static 'imagenes/carrusel4.jpg' %}" width=" 200 " height="200 " class="d-inline-block align-top " alt=" " loading="lazy ">

                    </div>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4 ">

                    <!-- Links -->
                    <h6 class="text-uppercase font-weight-bold ">Products</h6>
                    <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto " style="width: 60px; ">
                    <p>
                        <a href="#! ">Camas</a>
                    </p>
                    <p>
                        <a href="#! ">Roperos</a>
                    </p>
                    <p>
                        <a href="#! ">Closets</a>
                    </p>
                    <p>
                        <a href="#! ">Comodas</a>
                    </p>

                </div>
                <!-- Grid column -->


                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4 ">

                    <!-- Links -->
                    <h6 class="text-uppercase font-weight-bold ">Contact</h6>
                    <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto " style="width: 60px; ">
                    <p>
                        <i class="fas fa-home mr-3 "></i> Santiago, Santa victoria, 148</p>
                    <p>
                        <i class="fas fa-envelope mr-3 "></i>contacto@Muebles.LosPinos.cl</p>
                    <p>
                        <i class="fas fa-phone mr-3 "></i>9 30691339</p>


                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </div>
        <!-- Footer Links -->

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3 ">© 2020 Copyright:
            <a href="https://mdbootstrap.com/ "> MueblesLosPinos.com</a>
        </div>
        <!-- Copyright -->

    </footer>
    <!-- Footer -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js " integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo " crossorigin="anonymous "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js " integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49 " crossorigin="anonymous "></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js " integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV " crossorigin="anonymous "></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js " integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin=" anonymous "></script>
    <script src="{% static 'script.js' %} "></script>
</body>

</html>

productos/templates/detalle.html
{% extends "base.html" %} {% block content %}
{% load cart_tags %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1 class="text-center text-muted">Detalle del pedido #{{ order.id }}#</h1>
            <table class="table table-bordered">
                <thead>
                    <tr class="text-center">
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Precio/u</th>
                        <th>Precio total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_line in order.orderline_set.all %}
                       <tr class="text-center">
                            <td>{{ order_line.product.nombre }}</td>
                            <td>{{ order_line.quantity }}</td>
                            <td>${{ order_line.product.precio_venta|FormatoMoneda:"" }}</td>
                            <td>${{ order_line.product.precio_venta|Multiplicar:order_line.quantity|FormatoMoneda:"" }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td class="text-center">
                            <a>Total a Pagar :</a>${{ order.total|FormatoMoneda:"" }}
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
{% endblock %}

productos/templates/index.html
 {% extends "base.html" %} {% block content %}
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="static/imagenes/carrusel1.jpg" class="d-block w-100 " alt="...">
        </div>
        <div class="carousel-item">
            <img src="../static/imagenes/carrusel2.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="../static/imagenes/carrusel3.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<section id="galeria" class="container">

    <div class="text-center pt-5 ">
        <h1 class="text-info">Productos Insuperables</h1>
        <h4>diseños modernos</h4>
    </div>

    <div class="row">
        {% for muebles in productos%}
        <div class=" col-lg-4 col-md-3 col-sm-12 ">
            <div class="card">
                <img src="{{muebles.img}} " class="card-img-top" alt="{{muebles.nombre}} ">
                <div class="card-body text-center">
                    <h5 class="card-title"><i>{{muebles.especificacion}}</i></h5>
                    <p class="card-text"><i>precio: {{muebles.precio_venta}}</i></p>
                </div>
                <div class="card-footer text-center">
                    <a href="{% url 'carrito:AgregarProducto' muebles.id %}" class="btn btn-success">Añadir al carrito</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>

{% endblock %}

productos/templates/listadoOrden.html
{% extends "base.html" %} {% block content %}
{% load cart_tags %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="row">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Total</th>
                            <th>Fecha</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in object_list %}
                            <tr>
                                <td>{{ order.id }}</td>
                                <td>${{ order.total|FormatoMoneda:"" }}</td>
                                <td>{{ order.created_at|date:'d/m/Y H:i' }}</td>
                                <td><a href="{% url 'order_detail' order.id  %}" class="btn btn-info btn-sm">Ver detalle</a></td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4">
                                    <div class="alert alert-danger">No tienes ningún pedido todavía.</div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

productos/templates/productos.html
{% extends "base.html" %} {% block content %}
{% load cart_tags %}
<div class="wrap">
    <h1 class="text-info">Escoge una categoria de producto</h1>
    <div class="store-wrapper">
        <div class="category_list">
            {% for tip in tipo %}
            <a href="#" class="category_item" category="{{tip.descripcion}}">{{tip.descripcion}}</a> {% endfor %}
        </div>

        <div class="products-list">
            {% for muebles in prod %}
            <div class="product-item" category="{{muebles.id_tipo}}">
                <img src=" {{muebles.img}}" alt="">
                <a href="#">{{muebles.especificacion}}</a>
                <a>precio: {{muebles.precio_venta}}</a>
                <a href="{% url 'carrito:AgregarProducto' muebles.id %}" class="btn btn-success">Añadir al carrito</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

</div>
<div class="container mt-3">
    {% if messages %}
        <div class="row mt-3 mb-3">
            <div class="col-12">
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}    
</div>
{% endblock %}

productos/templates/promociones.html
{% extends "base.html" %} {% block content %}
<div class="wrap">
    <h1 class="text-info">Promociones</h1>
    <h4>Canal de Atención</h4>
    <br>
    <div class="store-wrapper">
        <div class="category_list">
            {% for canal in Can %}
            <a href="#" class="category_item" category="{{canal.descripcion}}">{{canal.descripcion}}</a> {% endfor %}
        </div>

        <div class="products-list">
            {% for pro in promo %}
            <div class="product-item" category="{{pro.canal}}">
                <img src=" {{pro.img}}" alt="">
                <a>{{pro.especificacion}}</a>
                <a>precio: {{pro.precio_nuevo}}</a>
                <a href="{% url 'carrito:AgregarProducto' pro.id %}" class="btn btn-success">Añadir al carrito</a>
            </div>
            {% endfor %}
        </div>
    </div>

</div>

</div>
<div class="container mt-3">
    {% if messages %}
        <div class="row mt-3 mb-3">
            <div class="col-12">
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}    
</div>
{% endblock %}

productos/templates/widget.html
{% extends "base.html" %} {% block content %}
{% load cart_tags %}
<table class="table table-bordered">
     <thead>
        <tr>
            <th colspan="3" class="text-center">
                Carrito de compras
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.carrito.items %}
           {% for key, value in request.session.carrito.items %}
                <tr class="text-center">
                    <td>{{ value.nombre }}</td>
                    <td>{{ value.cantidad }}</td>
                    <td>
                        <a
                            href="{% url 'carrito:AgregarProducto' value.producto_id %}"
                            class="btn btn-sm btn-success"
                        >
                            +
                        </a>
                        <a
                            href="{% url 'carrito:DecrementarProducto' value.producto_id %}"
                            class="ml-2 btn-sm btn btn-danger"
                        >
                            -
                        </a>
                        total {{ value.precio|Multiplicar:value.cantidad|FormatoMoneda:"$" }}
                    </td>
                </tr>
           {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        No tienes productos en el carrito
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{ MontoTotalCarrito|FormatoMoneda:"$" }}
            </td>
        </tr>
        {% if request.session.carrito.items %}
            <tr>
                <td colspan="3">
                    <a href="{% url 'process_order' %}" class="btn btn-success">Crear pedido</a>
                </td>
            </tr>
        {% endif %}
    </tfoot>
</table>
{% endblock %}